use super::{capabilities_from_name,AiProvider,ChatOutput,ChatRequest,ModelInfo,TokenSink,VisionInput};
use crate::{db::Database,error::{ObError,ObResult},models::{CapabilityState,ProviderStatus},secrets::SecretVault};
use async_trait::async_trait;
use futures_util::StreamExt;
use serde_json::{json,Value};
use tokio_util::sync::CancellationToken;

pub struct GeminiProvider{db:Database,vault:SecretVault,client:reqwest::Client}
impl GeminiProvider{
 pub fn new(db:Database,vault:SecretVault)->Self{Self{db,vault,client:reqwest::Client::builder().timeout(std::time::Duration::from_secs(180)).build().expect("HTTP client")}}
 fn base(&self)->String{self.db.execute(|c|Ok(c.query_row("SELECT COALESCE(base_url,'https://generativelanguage.googleapis.com/v1beta') FROM providers WHERE id='gemini'",[],|r|r.get(0))?)).unwrap_or_else(|_|"https://generativelanguage.googleapis.com/v1beta".into()).trim_end_matches('/').to_string()}
 fn key(&self)->ObResult<zeroize::Zeroizing<String>>{self.vault.get("gemini")}
 fn headers(&self,builder:reqwest::RequestBuilder)->ObResult<reqwest::RequestBuilder>{let key=self.key()?;Ok(builder.header("x-goog-api-key",key.as_str()).header("Content-Type","application/json"))}
 fn contents(request:&ChatRequest)->Vec<Value>{request.messages.iter().map(|m|json!({"role":if m.role=="assistant"{"model"}else{"user"},"parts":[{"text":m.content}]})).collect()}
 fn parse(value:&Value,model:&str)->ChatOutput{let candidate=value.pointer("/candidates/0");ChatOutput{text:candidate.and_then(|v|v.pointer("/content/parts/0/text")).and_then(Value::as_str).unwrap_or_default().into(),model:model.into(),usage:value.get("usageMetadata").cloned(),tool_calls:candidate.and_then(|v|v.pointer("/content/parts")).and_then(Value::as_array).into_iter().flatten().filter_map(|p|p.get("functionCall").cloned()).collect(),finish_reason:candidate.and_then(|v|v.get("finishReason")).and_then(Value::as_str).map(str::to_string)}}
}
#[async_trait] impl AiProvider for GeminiProvider{
 fn id(&self)->&'static str{"gemini"} fn label(&self)->&'static str{"Google Gemini"} fn capabilities(&self)->Vec<String>{vec!["chat".into(),"streaming".into(),"vision_model_dependent".into(),"embeddings".into(),"tool_calling_model_dependent".into()]}
 async fn test_connection(&self)->ObResult<ProviderStatus>{let models=self.list_models().await?;let active=self.db.execute(|c|Ok(c.query_row("SELECT active_model FROM providers WHERE id='gemini'",[],|r|r.get::<_,Option<String>>(0))?)).unwrap_or(None).or_else(||models.first().map(|m|m.id.clone()));Ok(ProviderStatus{id:self.id().into(),label:self.label().into(),state:CapabilityState::Available,active_model:active,capabilities:self.capabilities(),latency_ms:None,detail:Some(format!("{} compatible model(s)",models.len()))})}
 async fn list_models(&self)->ObResult<Vec<ModelInfo>>{let response=self.headers(self.client.get(format!("{}/models",self.base())))?.send().await?.error_for_status()?;let value:Value=response.json().await?;Ok(value.get("models").and_then(Value::as_array).into_iter().flatten().filter_map(|item|{let raw=item.get("name")?.as_str()?;let name=raw.trim_start_matches("models/").to_string();let methods=item.get("supportedGenerationMethods").and_then(Value::as_array).cloned().unwrap_or_default();if !methods.iter().any(|v|v.as_str()==Some("generateContent")){return None}Some(ModelInfo{id:name.clone(),name:name.clone(),capabilities:capabilities_from_name(&name),context_length:item.get("inputTokenLimit").and_then(Value::as_u64),size_bytes:None,local:false})}).collect())}
 async fn chat(&self,request:ChatRequest,cancellation:CancellationToken)->ObResult<ChatOutput>{let mut body=json!({"contents":Self::contents(&request),"generationConfig":{"temperature":request.temperature,"maxOutputTokens":request.max_tokens}});if let Some(system)=&request.system{body["systemInstruction"]=json!({"parts":[{"text":system}]})}if !request.tools.is_empty(){body["tools"]=json!([{"functionDeclarations":request.tools}])}let future=self.headers(self.client.post(format!("{}/models/{}:generateContent",self.base(),request.model)).json(&body))?.send();let response=tokio::select!{_ = cancellation.cancelled()=>return Err(ObError::Cancelled),value=future=>value?};let value:Value=response.error_for_status()?.json().await?;Ok(Self::parse(&value,&request.model))}
 async fn stream_chat(&self,request:ChatRequest,sink:TokenSink,cancellation:CancellationToken)->ObResult<ChatOutput>{let model=request.model.clone();let mut body=json!({"contents":Self::contents(&request),"generationConfig":{"temperature":request.temperature,"maxOutputTokens":request.max_tokens}});if let Some(system)=&request.system{body["systemInstruction"]=json!({"parts":[{"text":system}]})}let response=self.headers(self.client.post(format!("{}/models/{}:streamGenerateContent?alt=sse",self.base(),model)).json(&body))?.send().await?.error_for_status()?;let mut stream=response.bytes_stream();let mut buffer=String::new();let mut text=String::new();let mut last=json!({});loop{tokio::select!{_ = cancellation.cancelled()=>return Err(ObError::Cancelled),chunk=stream.next()=>match chunk{Some(Ok(bytes))=>{buffer.push_str(&String::from_utf8_lossy(&bytes));while let Some(index)=buffer.find('\n'){let line=buffer[..index].trim().to_string();buffer.drain(..=index);if let Some(data)=line.strip_prefix("data: "){if let Ok(value)=serde_json::from_str::<Value>(data){let parsed=Self::parse(&value,&model);if !parsed.text.is_empty(){text.push_str(&parsed.text);sink(parsed.text.clone())}last=value}}}},Some(Err(e))=>return Err(e.into()),None=>break}}}let mut out=Self::parse(&last,&model);out.text=text;Ok(out)}
 async fn vision(&self,input:VisionInput,cancellation:CancellationToken)->ObResult<ChatOutput>{let body=json!({"contents":[{"role":"user","parts":[{"text":input.prompt},{"inlineData":{"mimeType":input.mime_type,"data":input.data_base64}}]}]});let future=self.headers(self.client.post(format!("{}/models/{}:generateContent",self.base(),input.model)).json(&body))?.send();let response=tokio::select!{_ = cancellation.cancelled()=>return Err(ObError::Cancelled),value=future=>value?};let value:Value=response.error_for_status()?.json().await?;Ok(Self::parse(&value,&input.model))}
 async fn embeddings(&self,model:&str,input:&[String],cancellation:CancellationToken)->ObResult<Vec<Vec<f32>>>{let mut output=Vec::new();for text in input{let body=json!({"model":format!("models/{model}"),"content":{"parts":[{"text":text}]}});let future=self.headers(self.client.post(format!("{}/models/{}:embedContent",self.base(),model)).json(&body))?.send();let response=tokio::select!{_ = cancellation.cancelled()=>return Err(ObError::Cancelled),value=future=>value?};let value:Value=response.error_for_status()?.json().await?;output.push(serde_json::from_value(value.pointer("/embedding/values").cloned().ok_or_else(||ObError::Unavailable("Gemini embedding response was empty".into()))?)?)}Ok(output)}
 async fn tool_calling(&self,request:ChatRequest,cancellation:CancellationToken)->ObResult<ChatOutput>{self.chat(request,cancellation).await}
 async fn cancel(&self)->ObResult<()>{Ok(())}
}
