use super::{capabilities_from_name,AiProvider,ChatOutput,ChatRequest,ModelInfo,TokenSink,VisionInput};
use crate::{db::Database,error::{ObError,ObResult},models::{CapabilityState,ProviderStatus},secrets::SecretVault};
use async_trait::async_trait;
use futures_util::StreamExt;
use serde_json::{json,Value};
use tokio_util::sync::CancellationToken;

pub struct OpenAiCompatibleProvider{db:Database,vault:SecretVault,client:reqwest::Client}
impl OpenAiCompatibleProvider{
 pub fn new(db:Database,vault:SecretVault)->Self{Self{db,vault,client:reqwest::Client::builder().timeout(std::time::Duration::from_secs(180)).build().expect("HTTP client")}}
 fn base(&self)->String{self.db.execute(|c|Ok(c.query_row("SELECT COALESCE(base_url,'http://127.0.0.1:1234/v1') FROM providers WHERE id='openai-compatible'",[],|r|r.get(0))?)).unwrap_or_else(|_|"http://127.0.0.1:1234/v1".into()).trim_end_matches('/').to_string()}
 fn request(&self,builder:reqwest::RequestBuilder)->reqwest::RequestBuilder{match self.vault.get("openai-compatible"){Ok(key)=>builder.bearer_auth(key.as_str()),Err(_)=>builder}}
 fn messages(request:&ChatRequest)->Vec<Value>{let mut list:Vec<Value>=request.messages.iter().map(|m|json!({"role":m.role,"content":m.content})).collect();if let Some(system)=&request.system{list.insert(0,json!({"role":"system","content":system}))}list}
 fn parse(value:&Value,model:&str)->ChatOutput{let choice=value.pointer("/choices/0");ChatOutput{text:choice.and_then(|v|v.pointer("/message/content")).and_then(Value::as_str).unwrap_or_default().into(),model:value.get("model").and_then(Value::as_str).unwrap_or(model).into(),usage:value.get("usage").cloned(),tool_calls:choice.and_then(|v|v.pointer("/message/tool_calls")).and_then(Value::as_array).cloned().unwrap_or_default(),finish_reason:choice.and_then(|v|v.get("finish_reason")).and_then(Value::as_str).map(str::to_string)}}
}
#[async_trait] impl AiProvider for OpenAiCompatibleProvider{
 fn id(&self)->&'static str{"openai-compatible"} fn label(&self)->&'static str{"OpenAI Compatible"} fn capabilities(&self)->Vec<String>{vec!["chat".into(),"streaming".into(),"vision_model_dependent".into(),"embeddings_model_dependent".into(),"tool_calling_model_dependent".into()]}
 async fn test_connection(&self)->ObResult<ProviderStatus>{let models=self.list_models().await?;let active=self.db.execute(|c|Ok(c.query_row("SELECT active_model FROM providers WHERE id='openai-compatible'",[],|r|r.get::<_,Option<String>>(0))?)).unwrap_or(None).or_else(||models.first().map(|m|m.id.clone()));Ok(ProviderStatus{id:self.id().into(),label:self.label().into(),state:CapabilityState::Available,active_model:active,capabilities:self.capabilities(),latency_ms:None,detail:Some(format!("{} model(s) reported",models.len()))})}
 async fn list_models(&self)->ObResult<Vec<ModelInfo>>{let response=self.request(self.client.get(format!("{}/models",self.base()))).send().await.map_err(|_|ObError::NotConnected("OpenAI-compatible endpoint is unreachable".into()))?.error_for_status()?;let value:Value=response.json().await?;Ok(value.get("data").and_then(Value::as_array).into_iter().flatten().filter_map(|item|{let name=item.get("id")?.as_str()?.to_string();Some(ModelInfo{id:name.clone(),name:name.clone(),capabilities:capabilities_from_name(&name),context_length:item.get("context_length").and_then(Value::as_u64),size_bytes:None,local:self.base().starts_with("http://127.0.0.1")||self.base().starts_with("http://localhost")})}).collect())}
 async fn chat(&self,request:ChatRequest,cancellation:CancellationToken)->ObResult<ChatOutput>{let mut body=json!({"model":request.model,"messages":Self::messages(&request),"temperature":request.temperature,"max_tokens":request.max_tokens,"stream":false});if !request.tools.is_empty(){body["tools"]=json!(request.tools)}let future=self.request(self.client.post(format!("{}/chat/completions",self.base())).json(&body)).send();let response=tokio::select!{_ = cancellation.cancelled()=>return Err(ObError::Cancelled),value=future=>value?};let value:Value=response.error_for_status()?.json().await?;Ok(Self::parse(&value,&request.model))}
 async fn stream_chat(&self,request:ChatRequest,sink:TokenSink,cancellation:CancellationToken)->ObResult<ChatOutput>{let model=request.model.clone();let response=self.request(self.client.post(format!("{}/chat/completions",self.base())).json(&json!({"model":model,"messages":Self::messages(&request),"temperature":request.temperature,"max_tokens":request.max_tokens,"stream":true}))).send().await?.error_for_status()?;let mut stream=response.bytes_stream();let mut buffer=String::new();let mut text=String::new();let mut finish=None;loop{tokio::select!{_ = cancellation.cancelled()=>return Err(ObError::Cancelled),chunk=stream.next()=>match chunk{Some(Ok(bytes))=>{buffer.push_str(&String::from_utf8_lossy(&bytes));while let Some(index)=buffer.find('\n'){let line=buffer[..index].trim().to_string();buffer.drain(..=index);if let Some(data)=line.strip_prefix("data: "){if data=="[DONE]"{continue}if let Ok(value)=serde_json::from_str::<Value>(data){if let Some(token)=value.pointer("/choices/0/delta/content").and_then(Value::as_str){text.push_str(token);sink(token.into())}finish=value.pointer("/choices/0/finish_reason").and_then(Value::as_str).map(str::to_string)}}}},Some(Err(e))=>return Err(e.into()),None=>break}}}Ok(ChatOutput{text,model,usage:None,tool_calls:vec![],finish_reason:finish})}
 async fn vision(&self,input:VisionInput,cancellation:CancellationToken)->ObResult<ChatOutput>{let request=ChatRequest{model:input.model.clone(),messages:vec![],temperature:.2,max_tokens:2048,system:None,tools:vec![]};let body=json!({"model":input.model,"messages":[{"role":"user","content":[{"type":"text","text":input.prompt},{"type":"image_url","image_url":{"url":format!("data:{};base64,{}",input.mime_type,input.data_base64)}}]}]});let future=self.request(self.client.post(format!("{}/chat/completions",self.base())).json(&body)).send();let response=tokio::select!{_ = cancellation.cancelled()=>return Err(ObError::Cancelled),value=future=>value?};let value:Value=response.error_for_status()?.json().await?;Ok(Self::parse(&value,&request.model))}
 async fn embeddings(&self,model:&str,input:&[String],cancellation:CancellationToken)->ObResult<Vec<Vec<f32>>>{let future=self.request(self.client.post(format!("{}/embeddings",self.base())).json(&json!({"model":model,"input":input}))).send();let response=tokio::select!{_ = cancellation.cancelled()=>return Err(ObError::Cancelled),value=future=>value?};let value:Value=response.error_for_status()?.json().await?;Ok(value.get("data").and_then(Value::as_array).into_iter().flatten().filter_map(|item|serde_json::from_value(item.get("embedding")?.clone()).ok()).collect())}
 async fn tool_calling(&self,request:ChatRequest,cancellation:CancellationToken)->ObResult<ChatOutput>{self.chat(request,cancellation).await}
 async fn cancel(&self)->ObResult<()>{Ok(())}
}
