use crate::{db::Database,error::{ObError,ObResult},models::{AgentDefinition,AgentDescriptor}};
use rusqlite::params;
use serde::{Deserialize,Serialize};
use std::collections::{HashMap,HashSet,VecDeque};

#[derive(Debug,Clone,Serialize,Deserialize)]
#[serde(rename_all="camelCase")]
pub struct PlanStep{pub id:String,pub agent_id:String,pub instruction:String,pub depends_on:Vec<String>}
#[derive(Debug,Clone,Serialize,Deserialize)]
#[serde(rename_all="camelCase")]
pub struct TaskPlan{pub goal:String,pub steps:Vec<PlanStep>,pub max_concurrency:u8}

#[derive(Clone)] pub struct AgentRegistry{db:Database,definitions:Vec<AgentDefinition>}
impl AgentRegistry{
 pub fn load(db:Database)->ObResult<Self>{let definitions:Vec<AgentDefinition>=serde_json::from_str(include_str!("../../../agents/registry.json"))?;let now=chrono::Utc::now().to_rfc3339();for definition in &definitions{db.execute(|connection|{connection.execute("INSERT INTO agents(id,name,definition_json,enabled,updated_at) VALUES(?1,?2,?3,1,?4) ON CONFLICT(id) DO UPDATE SET name=excluded.name,definition_json=excluded.definition_json,updated_at=excluded.updated_at",params![definition.id,definition.name,serde_json::to_string(definition)?,now])?;Ok(())})?;}Ok(Self{db,definitions})}
 pub fn definitions(&self)->&[AgentDefinition]{&self.definitions}
 pub fn descriptors(&self)->ObResult<Vec<AgentDescriptor>>{let mut states:HashMap<String,(String,Option<String>,Option<String>)>=HashMap::new();self.db.execute(|connection|{let mut statement=connection.prepare("SELECT agent_id,state,input_json,parent_run_id FROM agent_runs WHERE completed_at IS NULL ORDER BY started_at DESC")?;let rows=statement.query_map([],|row|Ok((row.get::<_,String>(0)?,row.get::<_,String>(1)?,row.get::<_,String>(2)?,row.get::<_,Option<String>>(3)?)))?;for row in rows.flatten(){states.entry(row.0).or_insert((row.1,serde_json::from_str::<serde_json::Value>(&row.2).ok().and_then(|v|v.get("instruction").and_then(|v|v.as_str()).map(str::to_string)),row.3));}Ok(())})?;Ok(self.definitions.iter().cloned().map(|definition|{let state=states.get(&definition.id);AgentDescriptor{definition,state:state.map(|v|v.0.clone()).unwrap_or_else(||"idle".into()),current_task:state.and_then(|v|v.1.clone()),parent_agent:state.and_then(|v|v.2.clone()),collaborators:vec![]}}).collect())}
 pub fn plan(&self,request:&str)->TaskPlan{let lower=request.to_lowercase();let mut agents=vec!["task-planner"];if lower.contains("research"){agents.extend(["researcher","web-navigator","verification-agent"])}if ["code","build","debug","repository"].iter().any(|v|lower.contains(v)){agents.extend(["coding-engineer","debugger","code-reviewer","verification-agent"])}if ["file","folder","downloads","pdf"].iter().any(|v|lower.contains(v)){agents.extend(["file-intelligence","document-analyst","verification-agent"])}if ["screen","screenshot","visible"].iter().any(|v|lower.contains(v)){agents.extend(["screen-vision","ocr-specialist","verification-agent"])}if ["csv","spreadsheet","data"].iter().any(|v|lower.contains(v)){agents.extend(["data-analyst","verification-agent"])}let mut seen=HashSet::new();agents.retain(|id|seen.insert(*id));let steps=agents.iter().enumerate().map(|(index,id)|PlanStep{id:format!("step-{}",index+1),agent_id:(*id).into(),instruction:request.into(),depends_on:if index==0{vec![]}else if *id=="verification-agent"{(1..=index).map(|n|format!("step-{n}")).collect()}else{vec!["step-1".into()]}}).collect();TaskPlan{goal:request.into(),steps,max_concurrency:self.db.get_setting("max_agent_concurrency",10u8).clamp(1,10)}}
 pub fn validate_plan(plan:&TaskPlan)->ObResult<()>{let ids:HashSet<_>=plan.steps.iter().map(|s|s.id.as_str()).collect();if plan.steps.iter().any(|s|s.depends_on.iter().any(|d|!ids.contains(d.as_str()))){return Err(ObError::Validation("Task graph contains a missing dependency".into()))}let mut indegree:HashMap<&str,usize>=plan.steps.iter().map(|s|(s.id.as_str(),s.depends_on.len())).collect();let mut queue:VecDeque<&str>=indegree.iter().filter(|(_,v)|**v==0).map(|(k,_)|*k).collect();let mut visited=0;while let Some(id)=queue.pop_front(){visited+=1;for step in &plan.steps{if step.depends_on.iter().any(|d|d==id){if let Some(v)=indegree.get_mut(step.id.as_str()){*v-=1;if *v==0{queue.push_back(&step.id)}}}}}if visited!=plan.steps.len(){return Err(ObError::Validation("Task graph contains a cycle".into()))}Ok(())}
}
#[cfg(test)]mod tests{use super::*;#[test]fn generated_plans_are_acyclic(){let db=Database::memory().expect("db");let registry=AgentRegistry::load(db).expect("agents");let plan=registry.plan("Research and compare code editors");AgentRegistry::validate_plan(&plan).expect("valid plan");assert!(plan.steps.iter().any(|s|s.agent_id=="researcher"));}}
