use crate::{db::Database,error::{ObError,ObResult}};
use chrono::Utc;
use regex::Regex;
use rusqlite::{params,OptionalExtension};
use serde::{Deserialize,Serialize};
use std::cmp::Ordering;
use uuid::Uuid;

#[derive(Debug,Clone,Serialize,Deserialize)]#[serde(rename_all="camelCase")]
pub struct MemoryRecord{pub id:String,pub layer:String,pub content:String,pub source:String,pub created_at:String,pub metadata:serde_json::Value}
#[derive(Debug,Clone,Serialize,Deserialize)]#[serde(rename_all="camelCase")]
pub struct MemoryMatch{pub memory:MemoryRecord,pub semantic_score:f32,pub recency_score:f32,pub combined_score:f32}
#[derive(Clone)]pub struct MemoryStore{db:Database}
impl MemoryStore{
 pub fn new(db:Database)->Self{Self{db}}
 pub fn validate_content(content:&str)->ObResult<()> {let blocked=Regex::new(r"(?i)(password\s*[:=]|api[_ -]?key\s*[:=]|bearer\s+[a-z0-9._-]{12,}|(?:\d[ -]*?){13,19}|secret\s*[:=]|token\s*[:=])").expect("memory safety pattern");if blocked.is_match(content){return Err(ObError::SecurityBlocked("Sensitive credentials and payment-like data cannot be stored in memory".into()))}if content.trim().len()<3||content.len()>20000{return Err(ObError::Validation("Memory content length is invalid".into()))}Ok(())}
 pub fn store(&self,layer:&str,content:&str,source:&str,embedding:Option<(&str,&str,&[f32])>)->ObResult<MemoryRecord>{if !self.db.privacy().memory{return Err(ObError::PermissionRequired("Persistent memory is disabled".into()))}Self::validate_content(content)?;let allowed=["conversation","long_term","preference","behavioral_rule","episodic","semantic","task"];if !allowed.contains(&layer){return Err(ObError::Validation("Unknown memory layer".into()))}let id=Uuid::new_v4().to_string();let now=Utc::now().to_rfc3339();self.db.execute(|connection|{let tx=connection.unchecked_transaction()?;tx.execute("INSERT INTO memories(id,layer,content,source,sensitivity,approved,created_at,updated_at,metadata_json) VALUES(?1,?2,?3,?4,'normal',1,?5,?5,'{}')",params![id,layer,content,source,now])?;if let Some((provider,model,vector))=embedding{tx.execute("INSERT INTO memory_embeddings(memory_id,provider_id,model,vector_json,dimensions,created_at) VALUES(?1,?2,?3,?4,?5,?6)",params![id,provider,model,serde_json::to_string(vector)?,vector.len(),now])?;}tx.commit()?;Ok(())})?;Ok(MemoryRecord{id,layer:layer.into(),content:content.into(),source:source.into(),created_at:now,metadata:serde_json::json!({})})}
 pub fn search(&self,query:&str,query_embedding:Option<&[f32]>,limit:usize)->ObResult<Vec<MemoryMatch>>{let tokens:Vec<String>=query.to_lowercase().split_whitespace().filter(|v|v.len()>2).map(str::to_string).collect();let now=Utc::now();let mut rows=self.db.execute(|connection|{let mut statement=connection.prepare("SELECT m.id,m.layer,m.content,m.source,m.created_at,m.metadata_json,e.vector_json FROM memories m LEFT JOIN memory_embeddings e ON e.memory_id=m.id WHERE m.approved=1 ORDER BY m.created_at DESC LIMIT 1000")?;let mapped=statement.query_map([],|row|Ok((row.get::<_,String>(0)?,row.get::<_,String>(1)?,row.get::<_,String>(2)?,row.get::<_,String>(3)?,row.get::<_,String>(4)?,row.get::<_,String>(5)?,row.get::<_,Option<String>>(6)?)))?;Ok(mapped.flatten().collect::<Vec<_>>())})?.into_iter().map(|(id,layer,content,source,created,metadata,vector)|{let lexical=if tokens.is_empty(){0.0}else{tokens.iter().filter(|token|content.to_lowercase().contains(token.as_str())).count() as f32/tokens.len() as f32};let semantic=query_embedding.and_then(|q|vector.and_then(|v|serde_json::from_str::<Vec<f32>>(&v).ok()).map(|v|cosine(q,&v))).unwrap_or(lexical);let created_dt=chrono::DateTime::parse_from_rfc3339(&created).ok().map(|d|d.with_timezone(&Utc)).unwrap_or(now);let days=(now-created_dt).num_days().max(0) as f32;let recency=1.0/(1.0+days/14.0);MemoryMatch{memory:MemoryRecord{id,layer,content,source,created_at:created,metadata:serde_json::from_str(&metadata).unwrap_or_else(|_|serde_json::json!({}))},semantic_score:semantic,recency_score:recency,combined_score:semantic*.78+recency*.22}}).collect::<Vec<_>>();rows.sort_by(|a,b|b.combined_score.partial_cmp(&a.combined_score).unwrap_or(Ordering::Equal));rows.truncate(limit.clamp(1,50));Ok(rows)}
 pub fn delete(&self,id:&str)->ObResult<bool>{let changed=self.db.execute(|connection|Ok(connection.execute("DELETE FROM memories WHERE id=?1",[id])?))?;Ok(changed>0)}
 pub fn clear_all(&self)->ObResult<usize>{self.db.execute(|connection|Ok(connection.execute("DELETE FROM memories",[])?))}
 pub fn get(&self,id:&str)->ObResult<Option<MemoryRecord>>{self.db.execute(|connection|connection.query_row("SELECT id,layer,content,source,created_at,metadata_json FROM memories WHERE id=?1",[id],|row|Ok(MemoryRecord{id:row.get(0)?,layer:row.get(1)?,content:row.get(2)?,source:row.get(3)?,created_at:row.get(4)?,metadata:serde_json::from_str::<serde_json::Value>(&row.get::<_,String>(5)?).unwrap_or_else(|_|serde_json::json!({}))})).optional().map_err(Into::into))}
}
fn cosine(a:&[f32],b:&[f32])->f32{if a.len()!=b.len()||a.is_empty(){return 0.0}let(dot,aa,bb)=a.iter().zip(b).fold((0.0,0.0,0.0),|(d,x,y),(u,v)|(d+u*v,x+u*u,y+v*v));if aa==0.0||bb==0.0{0.0}else{dot/(aa.sqrt()*bb.sqrt())}}
#[cfg(test)]mod tests{use super::*;#[test]fn blocks_secrets(){assert!(MemoryStore::validate_content("api key = supersecretvalue").is_err());assert!(MemoryStore::validate_content("I prefer concise answers").is_ok())}#[test]fn vector_similarity_is_real(){assert!((cosine(&[1.0,0.0],&[1.0,0.0])-1.0).abs()<0.001);}}
