use crate::{error::{ObError,ObResult},models::{GpuSnapshot,SystemSnapshot}};
use chrono::Utc;
use serde::{Deserialize,Serialize};
use sysinfo::{Disks,Networks,System};

#[derive(Debug,Clone,Serialize,Deserialize)]#[serde(rename_all="camelCase")]
pub struct ProcessInfo{pub pid:u32,pub name:String,pub cpu_percent:f32,pub memory_bytes:u64,pub executable:Option<String>}

pub fn snapshot()->SystemSnapshot{let mut system=System::new_all();system.refresh_all();std::thread::sleep(std::time::Duration::from_millis(120));system.refresh_cpu_usage();let disks=Disks::new_with_refreshed_list();let networks=Networks::new_with_refreshed_list();let disk_total=disks.iter().map(|disk|disk.total_space()).sum::<u64>();let disk_available=disks.iter().map(|disk|disk.available_space()).sum::<u64>();let received=networks.iter().map(|(_,data)|data.total_received()).sum::<u64>();let transmitted=networks.iter().map(|(_,data)|data.total_transmitted()).sum::<u64>();let mut notes=vec!["CPU, memory, disk, network, and processes are read from the host through sysinfo.".into()];let gpu=read_windows_gpu(&mut notes);notes.push("Battery and temperature values remain unavailable when the operating system does not expose a supported sensor.".into());SystemSnapshot{measured_at:Utc::now(),cpu_percent:Some(system.global_cpu_usage()),memory_used_bytes:Some(system.used_memory()),memory_total_bytes:Some(system.total_memory()),disk_used_bytes:Some(disk_total.saturating_sub(disk_available)),disk_total_bytes:Some(disk_total),battery_percent:None,gpu,network_received_bytes:Some(received),network_transmitted_bytes:Some(transmitted),sensor_notes:notes}}

pub fn processes(limit:usize)->Vec<ProcessInfo>{let mut system=System::new_all();system.refresh_all();let mut values:Vec<_>=system.processes().iter().map(|(pid,process)|ProcessInfo{pid:pid.as_u32(),name:process.name().to_string_lossy().into_owned(),cpu_percent:process.cpu_usage(),memory_bytes:process.memory(),executable:process.exe().map(|p|p.to_string_lossy().into_owned())}).collect();values.sort_by(|a,b|b.memory_bytes.cmp(&a.memory_bytes));values.truncate(limit.clamp(1,200));values}

#[cfg(target_os="windows")]
fn read_windows_gpu(notes:&mut Vec<String>)->Vec<GpuSnapshot>{use std::process::Command;let script="Get-CimInstance Win32_VideoController | Select-Object Name,AdapterRAM | ConvertTo-Json -Compress";let output=Command::new("powershell.exe").args(["-NoProfile","-NonInteractive","-Command",script]).output();match output{Ok(value) if value.status.success()=>{let parsed:serde_json::Value=serde_json::from_slice(&value.stdout).unwrap_or(serde_json::json!([]));let list=if parsed.is_array(){parsed.as_array().cloned().unwrap_or_default()}else{vec![parsed]};notes.push("GPU name and adapter memory come from Win32_VideoController; utilization is unavailable without a vendor counter.".into());list.into_iter().filter_map(|item|Some(GpuSnapshot{name:item.get("Name")?.as_str()?.into(),utilization_percent:None,memory_used_bytes:None,memory_total_bytes:item.get("AdapterRAM").and_then(|v|v.as_u64())})).collect()},_=>{notes.push("GPU sensor query is unavailable on this host.".into());vec![]}}}
#[cfg(not(target_os="windows"))]fn read_windows_gpu(notes:&mut Vec<String>)->Vec<GpuSnapshot>{notes.push("Windows GPU telemetry is unavailable on this build host.".into());vec![]}

pub fn summary_text()->String{let snap=snapshot();let mut processes=processes(5);let lines=processes.drain(..).map(|process|format!("{} — {:.1}% CPU, {} MB RAM",process.name,process.cpu_percent,process.memory_bytes/1024/1024)).collect::<Vec<_>>().join("\n");let cpu=snap.cpu_percent.map(|value|format!("{value:.1}%")).unwrap_or_else(||"UNAVAILABLE".into());let used=snap.memory_used_bytes.map(|value|format!("{:.1} GB",value as f64/1_073_741_824.0)).unwrap_or_else(||"UNAVAILABLE".into());let total=snap.memory_total_bytes.map(|value|format!("{:.1} GB",value as f64/1_073_741_824.0)).unwrap_or_else(||"UNAVAILABLE".into());format!("Measured at {}\nCPU: {}\nRAM: {} / {}\nTop memory processes:\n{}",snap.measured_at,cpu,used,total,lines)}
